name: Publish new release
on:
  push:
    branches:
      - master

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: paralenz/actions/setup-node@master

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v2
      - uses: paralenz/actions/setup-node@master
      - name: Run tests
        run: yarn test

  publish:
    name: Publish release
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: paralenz/actions/setup-node@master
      - uses: paralenz/actions/publish-release@master

      # - name: Update Dependencies
      #   run: |
      #         ts-node ./scripts/update-all-dependants.ts