name: Publish new release
on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: familiohq/actions/setup-node@v2.1.8
      - name: Tests
        run: yarn test
      - name: Publish
        run: yarn publish
      - name: Tag and Release
        uses: familiohq/actions/make-release@v2.1.8